# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aleksandar Todorović (r3bl)
tagline:          Personal Blog
url:              http://r3bl.github.io/
paginate:         1
baseurl:          /
author:
  name:           Aleksandar Todorović
  url:            https:github.com/aleksandar-todorovic
  email:          aleksandar.todorovic@mail.ru

# Custom vars
version:          0.0.2
github:         https://github.com/aleksandar-todorovic
repo:           https://github.com/r3bl/r3bl.github.io

# Custom Pages
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
